/*
 * gen-meta.ts — generates src/data/meta.generated.ts from concepts.ts (run via `npm run gen:meta`).
 * The generated file carries ONLY lightweight nav/search metadata (no prose bodies), so the eager
 * TopBar / Sidebar / Footer / search can import it instead of concepts.ts and keep the full
 * bilingual content out of the index chunk (S19 bundle data-split). `npm run check:data` validates
 * meta ↔ concepts parity and fails if this file is stale — re-run gen:meta after editing metadata.
 */
import { writeFileSync } from 'node:fs';
import { modules, sections } from '../src/data/concepts';
import { glossary } from '../src/data/glossary'; // CHANGED (S21): emit a term-only search index too
import type { ModuleMeta } from '../src/data/types';

const modulesMeta: ModuleMeta[] = modules.map((m) => ({
  id: m.id,
  num: m.num,
  section: m.section,
  order: m.order,
  level: m.level,
  signature: !!m.signature,
  title: m.title,
  tagline: m.tagline,
  mentalModel: m.mentalModel,
  readMins: m.readMins,
  topics: m.topics.map((t) => ({ id: t.id, title: t.title })),
}));

const header =
  '// @generated by scripts/gen-meta.ts — DO NOT EDIT BY HAND.\n' +
  '// Run `npm run gen:meta` after changing module metadata. Lightweight nav/search data only\n' +
  '// (no prose bodies) — keeps concepts.ts content out of the eager index chunk (S19 data-split).\n' +
  "import type { ModuleMeta, Section } from './types';\n\n";

const body =
  `export const sectionsMeta: Section[] = ${JSON.stringify(sections, null, 2)};\n\n` +
  `export const modulesMeta: ModuleMeta[] = ${JSON.stringify(modulesMeta, null, 2)};\n`;

writeFileSync('src/data/meta.generated.ts', header + body, 'utf8');

// CHANGED (S21): a lightweight, term-ONLY glossary index for the eager global search.
// The full glossary (terms + bilingual definitions, ~47 KB) stays a lazy chunk; search only needs
// the English term strings to offer a hit that deep-links to the glossary page. check:data validates
// glossaryTerms ↔ glossary parity (same as meta) and fails if this file is stale.
const glossaryTerms: string[] = glossary.map((g) => g.term);
const gHeader =
  '// @generated by scripts/gen-meta.ts — DO NOT EDIT BY HAND.\n' +
  '// Run `npm run gen:meta` after changing glossary terms. Term strings only (no definitions) —\n' +
  '// keeps the 47 KB glossary out of the eager search index chunk (S21 search-ranking).\n\n';
const gBody = `export const glossaryTermIndex: string[] = ${JSON.stringify(glossaryTerms, null, 2)};\n`;
writeFileSync('src/data/glossaryTerms.generated.ts', gHeader + gBody, 'utf8');

console.log(
  `gen:meta — wrote ${modulesMeta.length} modules, ${sections.length} sections → meta.generated.ts; ` +
    `${glossaryTerms.length} glossary terms → glossaryTerms.generated.ts`,
);
