// @generated by scripts/gen-meta.ts — DO NOT EDIT BY HAND.
// Run `npm run gen:meta` after changing module metadata. Lightweight nav/search data only
// (no prose bodies) — keeps concepts.ts content out of the eager index chunk (S19 data-split).
import type { ModuleMeta, Section } from './types';

export const sectionsMeta: Section[] = [
  {
    "id": "s1-foundations",
    "roman": "I",
    "name": {
      "en": "Foundations & the landscape",
      "uk": "Основи та ландшафт"
    },
    "accent": "#5B9BD5",
    "blurb": {
      "en": "The on-ramp: what a database is, the family map, and SQL vs NoSQL trade-offs.",
      "uk": "Вхід у тему: що таке база даних, карта родин і компроміси SQL проти NoSQL."
    }
  },
  {
    "id": "s2-relational",
    "roman": "II",
    "name": {
      "en": "Relational design & SQL mastery",
      "uk": "Реляційний дизайн і майстерність SQL"
    },
    "accent": "#86BCEA",
    "blurb": {
      "en": "The PostgreSQL-centric spine: modeling, normalization, constraints, types, advanced SQL.",
      "uk": "PostgreSQL-центричний хребет: моделювання, нормалізація, constraints, типи, просунутий SQL."
    }
  },
  {
    "id": "s3-storage",
    "roman": "III",
    "name": {
      "en": "Storage & indexing internals",
      "uk": "Внутрішня будова зберігання та індексів"
    },
    "accent": "#A78BFA",
    "blurb": {
      "en": "Universal internals: pages & the heap, B-Tree/B+Tree, LSM, the index toolbox, query planning.",
      "uk": "Універсальні внутрішні механізми: pages і heap, B-Tree/B+Tree, LSM, набір індексів, планування запитів."
    }
  },
  {
    "id": "s4-transactions",
    "roman": "IV",
    "name": {
      "en": "Transactions & concurrency",
      "uk": "Транзакції та конкурентність"
    },
    "accent": "#6CC24A",
    "blurb": {
      "en": "ACID & the WAL, isolation levels & anomalies, MVCC vs locking, distributed transactions.",
      "uk": "ACID і WAL, isolation levels та аномалії, MVCC проти locking, розподілені транзакції."
    }
  },
  {
    "id": "s5-distribution",
    "roman": "V",
    "name": {
      "en": "Distribution, scale & reliability",
      "uk": "Розподіл, масштаб і надійність"
    },
    "accent": "#38BDF8",
    "blurb": {
      "en": "Replication, partitioning & sharding, CAP/PACELC & consensus, high availability & DR.",
      "uk": "Replication, partitioning і sharding, CAP/PACELC та consensus, висока доступність і DR."
    }
  },
  {
    "id": "s6-nosql",
    "roman": "VI",
    "name": {
      "en": "The NoSQL families in depth",
      "uk": "Родини NoSQL у деталях"
    },
    "accent": "#F2A93B",
    "blurb": {
      "en": "First-class coverage: document, key-value & caching, wide-column, graph.",
      "uk": "Повноцінне покриття: document, key-value і кешування, wide-column, graph."
    }
  },
  {
    "id": "s7-modern",
    "roman": "VII",
    "name": {
      "en": "Modern & specialized engines",
      "uk": "Сучасні та спеціалізовані движки"
    },
    "accent": "#C084FC",
    "blurb": {
      "en": "The modern wave: vector/AI, distributed SQL/NewSQL, analytics/columnar/time-series, cloud-native.",
      "uk": "Сучасна хвиля: vector/AI, distributed SQL/NewSQL, аналітика/columnar/time-series, cloud-native."
    }
  },
  {
    "id": "s8-mastery",
    "roman": "VIII",
    "name": {
      "en": "Mastery",
      "uk": "Майстерність"
    },
    "accent": "#34D399",
    "blurb": {
      "en": "Security, performance engineering, choosing the right database, and the mental-models gallery.",
      "uk": "Безпека, інженерія продуктивності, вибір правильної бази даних і галерея ментальних моделей."
    }
  }
];

export const modulesMeta: ModuleMeta[] = [
  {
    "id": "m1-what-is-a-database",
    "num": 1,
    "section": "s1-foundations",
    "order": 1,
    "level": "beginner",
    "signature": false,
    "title": {
      "en": "What a database is & why",
      "uk": "Що таке база даних і навіщо"
    },
    "tagline": {
      "en": "DBMS vs files, OLTP vs OLAP, and the cost of getting the model wrong.",
      "uk": "DBMS проти файлів, OLTP проти OLAP, і ціна неправильної моделі."
    },
    "mentalModel": {
      "en": "A DBMS is a contract over your data — concurrency, durability, integrity and querying you don't have to build yourself.",
      "uk": "DBMS — це контракт над вашими даними: concurrency, durability, цілісність і запити, які не треба будувати самому."
    },
    "readMins": 8,
    "topics": [
      {
        "id": "from-files-to-a-dbms",
        "title": {
          "en": "From files to a DBMS",
          "uk": "Від файлів до DBMS"
        }
      },
      {
        "id": "oltp-vs-olap",
        "title": {
          "en": "OLTP vs OLAP — two workload shapes",
          "uk": "OLTP проти OLAP — дві форми навантаження"
        }
      },
      {
        "id": "cost-of-getting-it-wrong",
        "title": {
          "en": "The cost of getting it wrong",
          "uk": "Ціна неправильного вибору"
        }
      },
      {
        "id": "the-vocabulary",
        "title": {
          "en": "The vocabulary, just enough to start",
          "uk": "Словник, рівно щоб почати"
        }
      }
    ]
  },
  {
    "id": "m2-landscape",
    "num": 2,
    "section": "s1-foundations",
    "order": 2,
    "level": "beginner",
    "signature": true,
    "title": {
      "en": "The database landscape",
      "uk": "Ландшафт баз даних"
    },
    "tagline": {
      "en": "The families map — relational, document, key-value, wide-column, graph, vector, time-series, search, OLAP.",
      "uk": "Карта родин — relational, document, key-value, wide-column, graph, vector, time-series, search, OLAP."
    },
    "mentalModel": {
      "en": "Fit the data model to the access pattern, not to the hype.",
      "uk": "Підбирайте модель даних під access pattern, а не під хайп."
    },
    "readMins": 9,
    "topics": [
      {
        "id": "the-families",
        "title": {
          "en": "The families",
          "uk": "Родини"
        }
      },
      {
        "id": "shape-of-data-drives-choice",
        "title": {
          "en": "The shape of your data drives the choice",
          "uk": "Форма даних визначає вибір"
        }
      },
      {
        "id": "engines-on-the-map",
        "title": {
          "en": "Engines on the map (2026)",
          "uk": "Движки на карті (2026)"
        }
      },
      {
        "id": "how-to-read-this-guide",
        "title": {
          "en": "How to read the rest of this guide",
          "uk": "Як читати решту посібника"
        }
      }
    ]
  },
  {
    "id": "m3-sql-vs-nosql",
    "num": 3,
    "section": "s1-foundations",
    "order": 3,
    "level": "middle",
    "signature": false,
    "title": {
      "en": "SQL vs NoSQL — the real trade-offs",
      "uk": "SQL проти NoSQL — справжні компроміси"
    },
    "tagline": {
      "en": "What 'NoSQL' actually means, and the strengths & weaknesses of each family.",
      "uk": "Що насправді означає «NoSQL», і сильні та слабкі сторони кожної родини."
    },
    "mentalModel": {
      "en": "'NoSQL' isn't 'no SQL' — it's trading joins and ACID for a specific shape and scale.",
      "uk": "«NoSQL» — це не «без SQL», а обмін joins та ACID на конкретну форму й масштаб."
    },
    "readMins": 11,
    "topics": [
      {
        "id": "what-nosql-means",
        "title": {
          "en": "What 'NoSQL' actually means (and doesn't)",
          "uk": "Що насправді означає «NoSQL» (і ні)"
        }
      },
      {
        "id": "relational-strengths",
        "title": {
          "en": "The relational strengths (and their cost)",
          "uk": "Сильні сторони relational (та їхня ціна)"
        }
      },
      {
        "id": "nosql-strengths",
        "title": {
          "en": "The NoSQL strengths (and their cost)",
          "uk": "Сильні сторони NoSQL (та їхня ціна)"
        }
      },
      {
        "id": "the-convergence",
        "title": {
          "en": "The convergence — the lines blur",
          "uk": "Конвергенція — межі розмиваються"
        }
      },
      {
        "id": "strengths-weaknesses-by-family",
        "title": {
          "en": "Strengths & weaknesses, family by family",
          "uk": "Сильні та слабкі сторони, родина за родиною"
        }
      }
    ]
  },
  {
    "id": "m4-relational-model",
    "num": 4,
    "section": "s1-foundations",
    "order": 4,
    "level": "beginner",
    "signature": false,
    "title": {
      "en": "The relational model & SQL foundations",
      "uk": "Реляційна модель та основи SQL"
    },
    "tagline": {
      "en": "Tables, keys, relationships, and the relational algebra behind SELECT.",
      "uk": "Таблиці, ключі, звʼязки та relational algebra за SELECT."
    },
    "mentalModel": {
      "en": "Think in sets, not loops: you declare what you want, not how to fetch it.",
      "uk": "Мисліть множинами, а не циклами: ви декларуєте що хочете, а не як це дістати."
    },
    "readMins": 11,
    "topics": [
      {
        "id": "tables-rows-columns-domains",
        "title": {
          "en": "Tables, rows, columns, domains",
          "uk": "Таблиці, рядки, колонки, domains"
        }
      },
      {
        "id": "keys-and-relationships",
        "title": {
          "en": "Keys & relationships",
          "uk": "Ключі та звʼязки"
        }
      },
      {
        "id": "relational-algebra-behind-select",
        "title": {
          "en": "The relational algebra behind SELECT",
          "uk": "Relational algebra за SELECT"
        }
      },
      {
        "id": "select-where-group-order",
        "title": {
          "en": "SELECT / WHERE / GROUP BY / ORDER BY",
          "uk": "SELECT / WHERE / GROUP BY / ORDER BY"
        }
      },
      {
        "id": "declarative-vs-imperative",
        "title": {
          "en": "Declarative vs imperative",
          "uk": "Декларативне проти імперативного"
        }
      }
    ]
  },
  {
    "id": "m5-anatomy-of-a-query",
    "num": 5,
    "section": "s1-foundations",
    "order": 5,
    "level": "middle",
    "signature": true,
    "title": {
      "en": "Anatomy of a query",
      "uk": "Анатомія запиту"
    },
    "tagline": {
      "en": "Parse → plan → execute → storage → result: the lifecycle every later module hangs off.",
      "uk": "Parse → plan → execute → storage → result: життєвий цикл, на якому тримається решта модулів."
    },
    "mentalModel": {
      "en": "SQL is a request, not a recipe — the planner decides how.",
      "uk": "SQL — це запит, а не рецепт: planner вирішує як."
    },
    "readMins": 10,
    "topics": [
      {
        "id": "the-lifecycle",
        "title": {
          "en": "The lifecycle of a query",
          "uk": "Життєвий цикл запиту"
        }
      },
      {
        "id": "logical-vs-physical-plan",
        "title": {
          "en": "Logical vs physical plan",
          "uk": "Логічний проти фізичного plan"
        }
      },
      {
        "id": "where-time-goes",
        "title": {
          "en": "Where the time goes",
          "uk": "Куди йде час"
        }
      },
      {
        "id": "why-this-matters",
        "title": {
          "en": "Why this matters",
          "uk": "Чому це важливо"
        }
      }
    ]
  },
  {
    "id": "m6-er-modeling",
    "num": 6,
    "section": "s2-relational",
    "order": 1,
    "level": "middle",
    "signature": true,
    "title": {
      "en": "ER modeling & schema design",
      "uk": "ER-моделювання та дизайн схеми"
    },
    "tagline": {
      "en": "Entities, relationships, cardinality, and the conceptual → logical → physical path.",
      "uk": "Entities, звʼязки, cardinality і шлях conceptual → logical → physical."
    },
    "mentalModel": {
      "en": "Model the nouns and their relationships first; tables come after.",
      "uk": "Спершу моделюйте іменники та їхні звʼязки; таблиці — потім."
    },
    "readMins": 11,
    "topics": [
      {
        "id": "entities-and-attributes",
        "title": {
          "en": "From ideas to entities & attributes",
          "uk": "Від ідей до entities та attributes"
        }
      },
      {
        "id": "relationships-and-cardinality",
        "title": {
          "en": "Relationships & cardinality",
          "uk": "Relationships і cardinality"
        }
      },
      {
        "id": "strong-weak-entities",
        "title": {
          "en": "Strong vs weak entities",
          "uk": "Strong проти weak entities"
        }
      },
      {
        "id": "design-lifecycle",
        "title": {
          "en": "Conceptual → logical → physical",
          "uk": "Conceptual → logical → physical"
        }
      },
      {
        "id": "modeling-smells",
        "title": {
          "en": "Common modeling smells & fixes",
          "uk": "Поширені smells моделювання та виправлення"
        }
      }
    ]
  },
  {
    "id": "m7-normalization",
    "num": 7,
    "section": "s2-relational",
    "order": 2,
    "level": "middle",
    "signature": true,
    "title": {
      "en": "Normalization & denormalization",
      "uk": "Нормалізація та денормалізація"
    },
    "tagline": {
      "en": "1NF→BCNF, functional dependencies, and when to denormalize on purpose.",
      "uk": "1NF→BCNF, functional dependencies і коли денормалізувати свідомо."
    },
    "mentalModel": {
      "en": "One fact, one place — until read performance makes you copy it deliberately.",
      "uk": "Один факт — одне місце, доки продуктивність читання не змусить свідомо його скопіювати."
    },
    "readMins": 12,
    "topics": [
      {
        "id": "functional-dependencies",
        "title": {
          "en": "Functional dependencies & why redundancy hurts",
          "uk": "Functional dependencies і чому надмірність шкодить"
        }
      },
      {
        "id": "normal-forms",
        "title": {
          "en": "1NF → 2NF → 3NF",
          "uk": "1NF → 2NF → 3NF"
        }
      },
      {
        "id": "bcnf",
        "title": {
          "en": "BCNF: when 3NF isn't enough",
          "uk": "BCNF: коли 3NF недостатньо"
        }
      },
      {
        "id": "denormalization",
        "title": {
          "en": "Denormalization on purpose",
          "uk": "Денормалізація свідомо"
        }
      }
    ]
  },
  {
    "id": "m8-keys-constraints",
    "num": 8,
    "section": "s2-relational",
    "order": 3,
    "level": "middle",
    "signature": false,
    "title": {
      "en": "Keys & constraints",
      "uk": "Ключі та constraints"
    },
    "tagline": {
      "en": "PK/FK/unique/candidate, referential actions, CHECK/NOT NULL/DEFAULT.",
      "uk": "PK/FK/unique/candidate, referential actions, CHECK/NOT NULL/DEFAULT."
    },
    "mentalModel": {
      "en": "Constraints are the database's last line of integrity — push invariants down into it.",
      "uk": "Constraints — остання лінія цілісності бази даних; проштовхуйте інваріанти в неї."
    },
    "readMins": 11,
    "topics": [
      {
        "id": "key-taxonomy",
        "title": {
          "en": "The key family: super → candidate → primary",
          "uk": "Сімʼя ключів: super → candidate → primary"
        }
      },
      {
        "id": "foreign-keys",
        "title": {
          "en": "Foreign keys & referential integrity",
          "uk": "Foreign keys і referential integrity"
        }
      },
      {
        "id": "constraint-toolbox",
        "title": {
          "en": "The constraint toolbox",
          "uk": "Набір constraints"
        }
      },
      {
        "id": "push-invariants-down",
        "title": {
          "en": "Push invariants into the database",
          "uk": "Проштовхуйте інваріанти в базу"
        }
      }
    ]
  },
  {
    "id": "m9-data-types",
    "num": 9,
    "section": "s2-relational",
    "order": 4,
    "level": "middle",
    "signature": true,
    "title": {
      "en": "Data types done right",
      "uk": "Типи даних правильно"
    },
    "tagline": {
      "en": "Strings, the FLOAT-for-money disaster, dates/zones, JSONB, arrays, enums, UUID.",
      "uk": "Рядки, катастрофа FLOAT для грошей, дати/zones, JSONB, масиви, enums, UUID."
    },
    "mentalModel": {
      "en": "A type is a constraint: the narrowest type that fits is the safest.",
      "uk": "Тип — це constraint: найвужчий тип, що підходить, — найбезпечніший."
    },
    "readMins": 12,
    "topics": [
      {
        "id": "type-is-a-constraint",
        "title": {
          "en": "A type is a constraint",
          "uk": "Тип — це constraint"
        }
      },
      {
        "id": "numbers-and-float",
        "title": {
          "en": "Numbers & the FLOAT-for-money disaster",
          "uk": "Числа і катастрофа FLOAT для грошей"
        }
      },
      {
        "id": "text-time-zones",
        "title": {
          "en": "Text, time & zones",
          "uk": "Текст, час і zones"
        }
      },
      {
        "id": "rich-types",
        "title": {
          "en": "Beyond scalars: JSONB, arrays, enums, UUID",
          "uk": "Поза скалярами: JSONB, масиви, enums, UUID"
        }
      }
    ]
  },
  {
    "id": "m10-sql-in-depth",
    "num": 10,
    "section": "s2-relational",
    "order": 5,
    "level": "senior",
    "signature": true,
    "title": {
      "en": "SQL in depth",
      "uk": "SQL поглиблено"
    },
    "tagline": {
      "en": "Joins and how they run, subqueries/CTEs, window functions, GROUPING/CUBE/ROLLUP, NULL logic.",
      "uk": "Joins і як вони виконуються, subqueries/CTEs, window functions, GROUPING/CUBE/ROLLUP, логіка NULL."
    },
    "mentalModel": {
      "en": "Most 'hard' SQL is a window function or a CTE you haven't reached for yet.",
      "uk": "Більшість «складного» SQL — це window function або CTE, до яких ви ще не дотягнулися."
    },
    "readMins": 14,
    "topics": [
      {
        "id": "joins-and-how-they-run",
        "title": {
          "en": "Joins & how they actually run",
          "uk": "Joins і як вони насправді виконуються"
        }
      },
      {
        "id": "subqueries-and-ctes",
        "title": {
          "en": "Subqueries & CTEs",
          "uk": "Subqueries і CTEs"
        }
      },
      {
        "id": "window-functions",
        "title": {
          "en": "Window functions",
          "uk": "Window functions"
        }
      },
      {
        "id": "aggregation-beyond-group-by",
        "title": {
          "en": "Aggregation beyond GROUP BY: ROLLUP, CUBE, GROUPING SETS",
          "uk": "Агрегація поза GROUP BY: ROLLUP, CUBE, GROUPING SETS"
        }
      },
      {
        "id": "null-three-valued-logic",
        "title": {
          "en": "NULL: the three-valued logic that bites everyone",
          "uk": "NULL: тризначна логіка, що кусає всіх"
        }
      }
    ]
  },
  {
    "id": "m11-views-procedural",
    "num": 11,
    "section": "s2-relational",
    "order": 6,
    "level": "senior",
    "signature": false,
    "title": {
      "en": "Views, procedural SQL & triggers",
      "uk": "Views, процедурний SQL і triggers"
    },
    "tagline": {
      "en": "Views vs materialized views, PL/pgSQL, triggers, and when logic belongs in the DB.",
      "uk": "Views проти materialized views, PL/pgSQL, triggers і коли логіці місце в БД."
    },
    "mentalModel": {
      "en": "Logic in the database is power and opacity in the same move — use it deliberately.",
      "uk": "Логіка в базі — це водночас сила і непрозорість; застосовуйте свідомо."
    },
    "readMins": 12,
    "topics": [
      {
        "id": "views",
        "title": {
          "en": "Views: a named query as an interface",
          "uk": "Views: іменований запит як інтерфейс"
        }
      },
      {
        "id": "materialized-views",
        "title": {
          "en": "Materialized views: trading freshness for speed",
          "uk": "Materialized views: міняємо свіжість на швидкість"
        }
      },
      {
        "id": "functions-procedures-plpgsql",
        "title": {
          "en": "Functions, procedures & PL/pgSQL",
          "uk": "Functions, procedures і PL/pgSQL"
        }
      },
      {
        "id": "triggers",
        "title": {
          "en": "Triggers & where logic should live",
          "uk": "Triggers і де має жити логіка"
        }
      }
    ]
  },
  {
    "id": "m12-storage",
    "num": 12,
    "section": "s3-storage",
    "order": 1,
    "level": "senior",
    "signature": false,
    "title": {
      "en": "How data is stored",
      "uk": "Як зберігаються дані"
    },
    "tagline": {
      "en": "The memory hierarchy, pages & the heap, row vs columnar, TOAST.",
      "uk": "Ієрархія памʼяті, pages і heap, row проти columnar, TOAST."
    },
    "mentalModel": {
      "en": "Disk is far; every design choice is about minimizing trips to it.",
      "uk": "Диск далеко; кожне рішення дизайну — про мінімізацію походів до нього."
    },
    "readMins": 13,
    "topics": [
      {
        "id": "memory-hierarchy",
        "title": {
          "en": "The memory hierarchy",
          "uk": "Ієрархія памʼяті"
        }
      },
      {
        "id": "pages-and-heap",
        "title": {
          "en": "Pages & the heap",
          "uk": "Pages і heap"
        }
      },
      {
        "id": "row-vs-columnar",
        "title": {
          "en": "Row-store vs column-store",
          "uk": "Row-store проти column-store"
        }
      },
      {
        "id": "toast-and-layout",
        "title": {
          "en": "Big values & layout",
          "uk": "Великі значення й розкладка"
        }
      }
    ]
  },
  {
    "id": "m13-btree",
    "num": 13,
    "section": "s3-storage",
    "order": 2,
    "level": "senior",
    "signature": true,
    "title": {
      "en": "B-Tree & B+Tree indexes",
      "uk": "B-Tree та B+Tree індекси"
    },
    "tagline": {
      "en": "Why a handful of page reads finds one row among billions — the data structure that makes databases fast.",
      "uk": "Чому кілька читань сторінок знаходять один рядок серед мільярдів — структура даних, що робить бази даних швидкими."
    },
    "mentalModel": {
      "en": "A B-Tree index is a shallow, very wide tree of disk pages. Each level is one page read, and the tree is only 3–5 levels deep even for billions of rows — so any row is a few hops from the root.",
      "uk": "B-Tree індекс — це неглибоке, дуже широке дерево з disk pages. Кожен level — це одне читання page, і дерево має лише 3–5 рівнів навіть для мільярдів рядків — тож будь-який рядок за кілька кроків від root."
    },
    "readMins": 18,
    "topics": [
      {
        "id": "why-not-array-bst",
        "title": {
          "en": "Why not a sorted array or a BST?",
          "uk": "Чому не відсортований масив чи BST?"
        }
      },
      {
        "id": "btree-structure",
        "title": {
          "en": "B-Tree structure & why O(log n)",
          "uk": "Структура B-Tree та чому O(log n)"
        }
      },
      {
        "id": "insert-split",
        "title": {
          "en": "Insert & split, delete & merge",
          "uk": "Вставка і split, видалення і merge"
        }
      },
      {
        "id": "bplus-tree",
        "title": {
          "en": "B+Tree: values in the leaves",
          "uk": "B+Tree: значення у leaves"
        }
      },
      {
        "id": "reading-the-plan",
        "title": {
          "en": "Reading an index plan: seq / index / index-only",
          "uk": "Читання плану: seq / index / index-only"
        }
      }
    ]
  },
  {
    "id": "m14-index-toolbox",
    "num": 14,
    "section": "s3-storage",
    "order": 3,
    "level": "senior",
    "signature": true,
    "title": {
      "en": "The index toolbox",
      "uk": "Набір індексів"
    },
    "tagline": {
      "en": "Hash, GIN/GiST/BRIN, full-text, covering/partial/expression — and what NOT to index.",
      "uk": "Hash, GIN/GiST/BRIN, full-text, covering/partial/expression — і що НЕ індексувати."
    },
    "mentalModel": {
      "en": "Pick the index to the query shape; each index is a write you pay for.",
      "uk": "Підбирайте index під форму запиту; кожен index — це запис, за який ви платите."
    },
    "readMins": 14,
    "topics": [
      {
        "id": "hash-and-the-toolbox",
        "title": {
          "en": "The toolbox & the hash index",
          "uk": "Набір інструментів і hash index"
        }
      },
      {
        "id": "specialized-indexes",
        "title": {
          "en": "The specialized index zoo",
          "uk": "Зоопарк спеціалізованих індексів"
        }
      },
      {
        "id": "full-text-search",
        "title": {
          "en": "Full-text search",
          "uk": "Повнотекстовий пошук"
        }
      },
      {
        "id": "index-shapes",
        "title": {
          "en": "Composite, covering, partial & expression",
          "uk": "Composite, covering, partial та expression"
        }
      },
      {
        "id": "cost-of-indexes",
        "title": {
          "en": "The cost of indexes",
          "uk": "Ціна індексів"
        }
      }
    ]
  },
  {
    "id": "m15-lsm",
    "num": 15,
    "section": "s3-storage",
    "order": 4,
    "level": "staff",
    "signature": true,
    "title": {
      "en": "LSM-trees & write-optimized storage",
      "uk": "LSM-trees і зберігання, оптимізоване під запис"
    },
    "tagline": {
      "en": "Memtable → SSTable → compaction; read/write/space amplification vs the B-Tree.",
      "uk": "Memtable → SSTable → compaction; read/write/space amplification проти B-Tree."
    },
    "mentalModel": {
      "en": "Buffer writes in memory, sort them later — trade read effort for write speed.",
      "uk": "Буферизуйте записи в памʼяті, сортуйте пізніше — міняйте зусилля читання на швидкість запису."
    },
    "readMins": 13,
    "topics": [
      {
        "id": "the-write-problem",
        "title": {
          "en": "The write problem",
          "uk": "Проблема запису"
        }
      },
      {
        "id": "lsm-design",
        "title": {
          "en": "Memtable, SSTable, compaction",
          "uk": "Memtable, SSTable, compaction"
        }
      },
      {
        "id": "reads-bloom-tombstones",
        "title": {
          "en": "Reads: Bloom filters & tombstones",
          "uk": "Читання: Bloom filters і tombstones"
        }
      },
      {
        "id": "amplification-triangle",
        "title": {
          "en": "The amplification triangle",
          "uk": "Трикутник amplification"
        }
      },
      {
        "id": "who-uses-it",
        "title": {
          "en": "Who uses it",
          "uk": "Хто це використовує"
        }
      }
    ]
  },
  {
    "id": "m16-query-planning",
    "num": 16,
    "section": "s3-storage",
    "order": 5,
    "level": "staff",
    "signature": true,
    "title": {
      "en": "Query planning & optimization",
      "uk": "Планування та оптимізація запитів"
    },
    "tagline": {
      "en": "Cost model, statistics, access paths, join order/algorithms, reading EXPLAIN ANALYZE.",
      "uk": "Cost model, statistics, access paths, порядок/алгоритми join, читання EXPLAIN ANALYZE."
    },
    "mentalModel": {
      "en": "The planner bets on statistics; bad estimates, bad plans.",
      "uk": "Planner робить ставку на statistics; погані оцінки — погані плани."
    },
    "readMins": 15,
    "topics": [
      {
        "id": "optimizers-job",
        "title": {
          "en": "The optimizer's job",
          "uk": "Робота оптимізатора"
        }
      },
      {
        "id": "statistics-cardinality",
        "title": {
          "en": "Statistics & cardinality estimation",
          "uk": "Statistics і оцінка cardinality"
        }
      },
      {
        "id": "access-paths-joins",
        "title": {
          "en": "Access paths & join algorithms",
          "uk": "Access paths і алгоритми join"
        }
      },
      {
        "id": "reading-explain",
        "title": {
          "en": "Reading EXPLAIN (ANALYZE)",
          "uk": "Читання EXPLAIN (ANALYZE)"
        }
      },
      {
        "id": "helping-the-planner",
        "title": {
          "en": "Helping the planner",
          "uk": "Як допомогти planner"
        }
      }
    ]
  },
  {
    "id": "m17-acid-wal",
    "num": 17,
    "section": "s4-transactions",
    "order": 1,
    "level": "senior",
    "signature": true,
    "title": {
      "en": "ACID & durability",
      "uk": "ACID та durability"
    },
    "tagline": {
      "en": "The four guarantees, the Write-Ahead Log, commit & crash recovery.",
      "uk": "Чотири гарантії, Write-Ahead Log, commit і відновлення після збою."
    },
    "mentalModel": {
      "en": "Write your intentions down first (the WAL); then it's safe to change the data.",
      "uk": "Спершу запишіть наміри (WAL); потім безпечно змінювати дані."
    },
    "readMins": 13,
    "topics": [
      {
        "id": "four-guarantees",
        "title": {
          "en": "The four guarantees",
          "uk": "Чотири гарантії"
        }
      },
      {
        "id": "the-wal",
        "title": {
          "en": "The Write-Ahead Log",
          "uk": "Write-Ahead Log"
        }
      },
      {
        "id": "commit-recovery",
        "title": {
          "en": "Commit & crash recovery",
          "uk": "Commit і відновлення після збою"
        }
      },
      {
        "id": "consistency-vs-cap",
        "title": {
          "en": "“Consistency” here vs in CAP",
          "uk": "«Consistency» тут проти CAP"
        }
      }
    ]
  },
  {
    "id": "m18-isolation",
    "num": 18,
    "section": "s4-transactions",
    "order": 2,
    "level": "staff",
    "signature": true,
    "title": {
      "en": "Isolation levels & anomalies",
      "uk": "Isolation levels та аномалії"
    },
    "tagline": {
      "en": "Dirty/non-repeatable/phantom/lost-update/write-skew; the SQL levels vs what engines really do.",
      "uk": "Dirty/non-repeatable/phantom/lost-update/write-skew; рівні SQL проти того, що движки роблять насправді."
    },
    "mentalModel": {
      "en": "Isolation is the illusion that you're alone — each level buys more of it for more cost.",
      "uk": "Isolation — це ілюзія, що ви самі; кожен рівень купує її більше за більшу ціну."
    },
    "readMins": 15,
    "topics": [
      {
        "id": "the-anomalies",
        "title": {
          "en": "The anomalies",
          "uk": "Аномалії"
        }
      },
      {
        "id": "the-levels",
        "title": {
          "en": "The SQL standard levels",
          "uk": "Рівні SQL-стандарту"
        }
      },
      {
        "id": "standard-vs-reality",
        "title": {
          "en": "Standard vs reality",
          "uk": "Стандарт проти реальності"
        }
      },
      {
        "id": "serializable",
        "title": {
          "en": "Serializable & the cost of correctness",
          "uk": "Serializable і ціна коректності"
        }
      }
    ]
  },
  {
    "id": "m19-mvcc",
    "num": 19,
    "section": "s4-transactions",
    "order": 3,
    "level": "staff",
    "signature": true,
    "title": {
      "en": "Concurrency control",
      "uk": "Контроль конкурентності"
    },
    "tagline": {
      "en": "MVCC vs locking, 2PL, snapshot visibility, deadlocks, vacuum & bloat.",
      "uk": "MVCC проти locking, 2PL, видимість snapshot, deadlocks, vacuum і bloat."
    },
    "mentalModel": {
      "en": "Everyone reads their own snapshot; readers don't block writers — and the bill is garbage to collect.",
      "uk": "Кожен читає власний snapshot; читачі не блокують записувачів — а рахунок — це сміття, яке треба прибрати."
    },
    "readMins": 14,
    "topics": [
      {
        "id": "pessimistic-vs-optimistic",
        "title": {
          "en": "Pessimistic vs optimistic",
          "uk": "Песимістичний проти оптимістичного"
        }
      },
      {
        "id": "mvcc-mechanism",
        "title": {
          "en": "MVCC — versions, snapshots, visibility",
          "uk": "MVCC — версії, snapshots, видимість"
        }
      },
      {
        "id": "locking-2pl-deadlocks",
        "title": {
          "en": "Locking, 2PL & deadlocks",
          "uk": "Locking, 2PL і deadlocks"
        }
      },
      {
        "id": "cost-of-mvcc",
        "title": {
          "en": "The cost of MVCC: bloat, vacuum & wraparound",
          "uk": "Ціна MVCC: bloat, vacuum і wraparound"
        }
      }
    ]
  },
  {
    "id": "m20-distributed-tx",
    "num": 20,
    "section": "s4-transactions",
    "order": 4,
    "level": "staff",
    "signature": true,
    "title": {
      "en": "Distributed transactions",
      "uk": "Розподілені транзакції"
    },
    "tagline": {
      "en": "2PC and its blocking problem, sagas & compensation, the outbox, idempotency, the exactly-once myth.",
      "uk": "2PC і його проблема блокування, sagas і компенсація, outbox, idempotency, міф exactly-once."
    },
    "mentalModel": {
      "en": "Across machines you agree then act — or you undo. There is no shared commit, and 'exactly-once' is a myth.",
      "uk": "Між машинами ви домовляєтесь, тоді дієте — або відкочуєте. Спільного commit немає, а «exactly-once» — міф."
    },
    "readMins": 13,
    "topics": [
      {
        "id": "why-distribution-breaks-acid",
        "title": {
          "en": "Why distribution breaks single-node ACID",
          "uk": "Чому розподіл ламає однонодовий ACID"
        }
      },
      {
        "id": "two-phase-commit",
        "title": {
          "en": "Two-phase commit & its blocking problem",
          "uk": "Two-phase commit і його проблема блокування"
        }
      },
      {
        "id": "sagas",
        "title": {
          "en": "Sagas & compensation",
          "uk": "Sagas і компенсація"
        }
      },
      {
        "id": "outbox-idempotency",
        "title": {
          "en": "The outbox, idempotency & the exactly-once myth",
          "uk": "Outbox, idempotency і міф exactly-once"
        }
      }
    ]
  },
  {
    "id": "m21-replication",
    "num": 21,
    "section": "s5-distribution",
    "order": 1,
    "level": "senior",
    "signature": true,
    "title": {
      "en": "Replication",
      "uk": "Replication"
    },
    "tagline": {
      "en": "Leader/follower, sync vs async, physical vs logical, failover, replication lag.",
      "uk": "Leader/follower, sync проти async, physical проти logical, failover, replication lag."
    },
    "mentalModel": {
      "en": "Copies cost you latency or safety — pick which one consciously.",
      "uk": "Копії коштують вам latency або safety — обирайте свідомо."
    },
    "readMins": 14,
    "topics": [
      {
        "id": "streaming-replication-how-it-works",
        "title": {
          "en": "How streaming replication works",
          "uk": "Як працює streaming replication"
        }
      },
      {
        "id": "sync-vs-async",
        "title": {
          "en": "Sync vs async — the durability/latency trade",
          "uk": "Sync проти async — компроміс надійності та затримки"
        }
      },
      {
        "id": "physical-vs-logical",
        "title": {
          "en": "Physical vs logical replication",
          "uk": "Physical проти logical replication"
        }
      },
      {
        "id": "replication-lag-monitoring",
        "title": {
          "en": "Replication lag & monitoring",
          "uk": "Replication lag та моніторинг"
        }
      },
      {
        "id": "failover-patroni",
        "title": {
          "en": "Failover & HA with Patroni",
          "uk": "Failover та HA з Patroni"
        }
      }
    ]
  },
  {
    "id": "m22-sharding",
    "num": 22,
    "section": "s5-distribution",
    "order": 2,
    "level": "senior",
    "signature": true,
    "title": {
      "en": "Partitioning & sharding",
      "uk": "Partitioning та sharding"
    },
    "tagline": {
      "en": "Vertical/horizontal, the shard key, routing & rebalancing, hotspots.",
      "uk": "Vertical/horizontal, shard key, маршрутизація і ребалансування, hotspots."
    },
    "mentalModel": {
      "en": "The shard key is destiny — it decides every future query and hotspot.",
      "uk": "Shard key — це доля: він вирішує кожен майбутній запит і hotspot."
    },
    "readMins": 13,
    "topics": [
      {
        "id": "pg-table-partitioning",
        "title": {
          "en": "Table partitioning in PostgreSQL",
          "uk": "Partitioning таблиць у PostgreSQL"
        }
      },
      {
        "id": "sharding-when-and-why",
        "title": {
          "en": "Sharding — when and why",
          "uk": "Sharding — коли і чому"
        }
      },
      {
        "id": "shard-key-and-hotspots",
        "title": {
          "en": "The shard key — destiny and hotspots",
          "uk": "Shard key — доля та hotspots"
        }
      },
      {
        "id": "cross-shard-operations",
        "title": {
          "en": "Cross-shard operations — the price of distribution",
          "uk": "Cross-shard-операції — ціна розподілу"
        }
      }
    ]
  },
  {
    "id": "m23-cap",
    "num": 23,
    "section": "s5-distribution",
    "order": 3,
    "level": "staff",
    "signature": true,
    "title": {
      "en": "CAP, PACELC & consensus",
      "uk": "CAP, PACELC та consensus"
    },
    "tagline": {
      "en": "CAP stated precisely, PACELC's latency trade, consistency models, quorums, Raft/Paxos.",
      "uk": "CAP точно сформульований, компроміс latency у PACELC, моделі consistency, quorums, Raft/Paxos."
    },
    "mentalModel": {
      "en": "During a partition you answer wrong or not at all — CAP is that choice. PACELC adds: even without a partition, you trade latency for consistency.",
      "uk": "Під час partition ви відповідаєте неправильно або ніяк — CAP саме про цей вибір. PACELC додає: навіть без partition ви обмінюєте latency на consistency."
    },
    "readMins": 13,
    "topics": [
      {
        "id": "cap-stated-precisely",
        "title": {
          "en": "CAP stated precisely — and the partition you cannot opt out of",
          "uk": "CAP сформульований точно — та partition, від якої не відмовитися"
        }
      },
      {
        "id": "pacelc",
        "title": {
          "en": "PACELC — the latency trade even without a partition",
          "uk": "PACELC — компроміс latency навіть без partition"
        }
      },
      {
        "id": "consistency-models",
        "title": {
          "en": "Consistency models — from strong to weak",
          "uk": "Моделі consistency — від сильних до слабких"
        }
      },
      {
        "id": "consensus-raft-paxos",
        "title": {
          "en": "Consensus — quorums, Raft and Paxos",
          "uk": "Consensus — quorums, Raft та Paxos"
        }
      }
    ]
  },
  {
    "id": "m24-ha-backups-dr",
    "num": 24,
    "section": "s5-distribution",
    "order": 4,
    "level": "senior",
    "signature": false,
    "title": {
      "en": "High availability, backups & DR",
      "uk": "Висока доступність, backups і DR"
    },
    "tagline": {
      "en": "Patroni/etcd, PITR & the WAL archive, RPO/RTO, testing restores.",
      "uk": "Patroni/etcd, PITR і WAL archive, RPO/RTO, тестування відновлень."
    },
    "mentalModel": {
      "en": "HA is fast failover; DR is surviving the region — and an untested backup doesn't exist.",
      "uk": "HA — це швидкий failover; DR — пережити втрату регіону; а неперевірений backup не існує."
    },
    "readMins": 11,
    "topics": [
      {
        "id": "ha-patroni",
        "title": {
          "en": "HA building blocks — Patroni, etcd and automatic failover",
          "uk": "Компоненти HA — Patroni, etcd та автоматичний failover"
        }
      },
      {
        "id": "backups",
        "title": {
          "en": "Backups — logical vs physical, pgBackRest and Barman",
          "uk": "Backups — logical проти physical, pgBackRest та Barman"
        }
      },
      {
        "id": "pitr",
        "title": {
          "en": "PITR — Point-in-Time Recovery and the WAL archive",
          "uk": "PITR — Point-in-Time Recovery та WAL archive"
        }
      },
      {
        "id": "rpo-rto-testing",
        "title": {
          "en": "RPO, RTO and testing recovery — the backup you never restored",
          "uk": "RPO, RTO та тестування відновлення — backup, який ніколи не відновлювали"
        }
      }
    ]
  },
  {
    "id": "m25-document",
    "num": 25,
    "section": "s6-nosql",
    "order": 1,
    "level": "middle",
    "signature": false,
    "title": {
      "en": "Document databases",
      "uk": "Document databases"
    },
    "tagline": {
      "en": "MongoDB's model & internals, embed vs reference, the aggregation pipeline.",
      "uk": "Модель і внутрішня будова MongoDB, embed проти reference, aggregation pipeline."
    },
    "mentalModel": {
      "en": "Store together what you read together — the document is your access pattern.",
      "uk": "Зберігайте разом те, що читаєте разом — document і є вашим access pattern."
    },
    "readMins": 13,
    "topics": [
      {
        "id": "document-model",
        "title": {
          "en": "The document model — BSON, collections, flexible schema",
          "uk": "Модель document — BSON, collections, flexible schema"
        }
      },
      {
        "id": "embed-vs-reference",
        "title": {
          "en": "Embed vs reference — model for the access pattern",
          "uk": "Embed проти reference — моделюйте для access pattern"
        }
      },
      {
        "id": "indexing-aggregation",
        "title": {
          "en": "Indexing & the aggregation pipeline",
          "uk": "Indexing та aggregation pipeline"
        }
      },
      {
        "id": "transactions-internals",
        "title": {
          "en": "Transactions, consistency & internals",
          "uk": "Transactions, consistency і внутрішня будова"
        }
      },
      {
        "id": "when-document-fits",
        "title": {
          "en": "When document fits — and when you're hiding a relational model",
          "uk": "Коли document підходить — і коли ви приховуєте реляційну модель"
        }
      }
    ]
  },
  {
    "id": "m26-key-value",
    "num": 26,
    "section": "s6-nosql",
    "order": 2,
    "level": "middle",
    "signature": false,
    "title": {
      "en": "Key-value & caching",
      "uk": "Key-value та кешування"
    },
    "tagline": {
      "en": "Redis/Valkey data structures, caching patterns, eviction & persistence, the 2024 license fork.",
      "uk": "Структури Redis/Valkey, патерни кешування, eviction і persistence, ліцензійний fork 2024."
    },
    "mentalModel": {
      "en": "Fast because it forgets — and because it lives in memory.",
      "uk": "Швидкий, бо забуває — і бо живе в памʼяті."
    },
    "readMins": 13,
    "topics": [
      {
        "id": "kv-data-structures",
        "title": {
          "en": "The KV model & Redis/Valkey data structures",
          "uk": "Модель KV та структури даних Redis/Valkey"
        }
      },
      {
        "id": "caching-patterns",
        "title": {
          "en": "Caching patterns — cache-aside, write-through, TTL, stampede",
          "uk": "Патерни кешування — cache-aside, write-through, TTL, stampede"
        }
      },
      {
        "id": "eviction-persistence",
        "title": {
          "en": "Eviction & persistence — LRU/LFU, RDB vs AOF",
          "uk": "Eviction і persistence — LRU/LFU, RDB проти AOF"
        }
      },
      {
        "id": "redis-valkey-story",
        "title": {
          "en": "The Redis → Valkey story — the 2024 license change and its aftermath",
          "uk": "Історія Redis → Valkey — зміна ліцензії 2024 р. та її наслідки"
        }
      },
      {
        "id": "beyond-cache",
        "title": {
          "en": "Beyond cache — locks, queues, pub/sub, rate limiting",
          "uk": "Поза кешем — locks, queues, pub/sub, rate limiting"
        }
      }
    ]
  },
  {
    "id": "m27-wide-column",
    "num": 27,
    "section": "s6-nosql",
    "order": 3,
    "level": "senior",
    "signature": false,
    "title": {
      "en": "Wide-column stores",
      "uk": "Wide-column stores"
    },
    "tagline": {
      "en": "Cassandra & ScyllaDB: partition/clustering model, tunable consistency, LSM heritage.",
      "uk": "Cassandra і ScyllaDB: partition/clustering модель, tunable consistency, LSM-спадщина."
    },
    "mentalModel": {
      "en": "Design your table around the query: the partition key is the only free WHERE clause.",
      "uk": "Проектуйте таблицю під запит: partition key — єдиний безкоштовний WHERE clause."
    },
    "readMins": 15,
    "topics": [
      {
        "id": "partition-clustering-model",
        "title": {
          "en": "The partition/clustering model — wide rows",
          "uk": "Partition/clustering модель — wide rows"
        }
      },
      {
        "id": "ring-architecture",
        "title": {
          "en": "Ring architecture — peer-to-peer, vnodes, gossip",
          "uk": "Ring-архітектура — peer-to-peer, vnodes, gossip"
        }
      },
      {
        "id": "tunable-consistency",
        "title": {
          "en": "Tunable consistency — the W + R > RF formula",
          "uk": "Tunable consistency — формула W + R > RF"
        }
      },
      {
        "id": "lsm-storage-compaction",
        "title": {
          "en": "LSM storage — memtable, SSTables & compaction",
          "uk": "LSM storage — memtable, SSTables і compaction"
        }
      },
      {
        "id": "cql-query-first",
        "title": {
          "en": "CQL & query-first data modeling",
          "uk": "CQL і query-first моделювання даних"
        }
      }
    ]
  },
  {
    "id": "m28-graph",
    "num": 28,
    "section": "s6-nosql",
    "order": 4,
    "level": "senior",
    "signature": false,
    "title": {
      "en": "Graph databases",
      "uk": "Graph databases"
    },
    "tagline": {
      "en": "Property graph vs RDF, index-free adjacency, Cypher & GQL, when relationships ARE the data.",
      "uk": "Property graph проти RDF, index-free adjacency, Cypher і GQL, коли relationships — це і є дані."
    },
    "mentalModel": {
      "en": "When the relationships between things are as important as the things themselves — use a graph.",
      "uk": "Коли звʼязки між речами так само важливі, як і самі речі — використовуй graph."
    },
    "readMins": 14,
    "topics": [
      {
        "id": "property-graph-model",
        "title": {
          "en": "The labeled property graph — nodes, relationships, properties",
          "uk": "Labeled property graph — nodes, relationships, properties"
        }
      },
      {
        "id": "index-free-adjacency",
        "title": {
          "en": "Index-free adjacency — why graph traversal is fast",
          "uk": "Index-free adjacency — чому graph traversal швидкий"
        }
      },
      {
        "id": "cypher-gql",
        "title": {
          "en": "Cypher, openCypher & GQL",
          "uk": "Cypher, openCypher і GQL"
        }
      },
      {
        "id": "graph-algorithms-use-cases",
        "title": {
          "en": "Graph algorithms & canonical use cases",
          "uk": "Graph algorithms і канонічні випадки використання"
        }
      },
      {
        "id": "graph-when-to-use",
        "title": {
          "en": "When graphs shine — and when they do not",
          "uk": "Коли graphs блищать — і коли ні"
        }
      }
    ]
  },
  {
    "id": "m29-vector",
    "num": 29,
    "section": "s7-modern",
    "order": 1,
    "level": "senior",
    "signature": true,
    "title": {
      "en": "Vector Databases & AI",
      "uk": "Vector Databases та AI"
    },
    "tagline": {
      "en": "Embeddings, ANN/HNSW, pgvector vs dedicated vector DBs, and RAG",
      "uk": "Embeddings, ANN/HNSW, pgvector проти спеціалізованих vector DBs та RAG"
    },
    "mentalModel": {
      "en": "A vector DB stores points in high-dimensional space and finds the nearest neighbours fast — trading exact recall for speed via HNSW graph navigation.",
      "uk": "Vector DB зберігає точки у багатовимірному просторі та швидко знаходить найближчих сусідів, жертвуючи точним recall заради швидкості через навігацію HNSW графом."
    },
    "readMins": 13,
    "topics": [
      {
        "id": "what-are-embeddings",
        "title": {
          "en": "Embeddings & similarity search",
          "uk": "Embeddings та пошук схожості"
        }
      },
      {
        "id": "ann-hnsw",
        "title": {
          "en": "Exact kNN vs ANN — HNSW",
          "uk": "Exact kNN проти ANN — HNSW"
        }
      },
      {
        "id": "pgvector",
        "title": {
          "en": "pgvector — vector search inside PostgreSQL",
          "uk": "pgvector — vector search усередині PostgreSQL"
        }
      },
      {
        "id": "dedicated-vector-dbs",
        "title": {
          "en": "Dedicated vector databases",
          "uk": "Спеціалізовані vector databases"
        }
      },
      {
        "id": "rag",
        "title": {
          "en": "RAG — Retrieval-Augmented Generation",
          "uk": "RAG — Retrieval-Augmented Generation"
        }
      }
    ]
  },
  {
    "id": "m30-distributed-sql",
    "num": 30,
    "section": "s7-modern",
    "order": 2,
    "level": "staff",
    "signature": false,
    "title": {
      "en": "Distributed SQL / NewSQL",
      "uk": "Distributed SQL / NewSQL"
    },
    "tagline": {
      "en": "CockroachDB, TiDB, YugabyteDB, Spanner, Aurora DSQL — and why Postgres won the API",
      "uk": "CockroachDB, TiDB, YugabyteDB, Spanner, Aurora DSQL — і чому Postgres виграв API"
    },
    "mentalModel": {
      "en": "NewSQL = distributed storage + Raft consensus + (often) a Postgres wire — ACID guarantees at horizontal scale without the dual-write problem.",
      "uk": "NewSQL = розподілене зберігання + Raft consensus + (часто) Postgres wire — ACID-гарантії при горизонтальному масштабі без проблеми dual-write."
    },
    "readMins": 12,
    "topics": [
      {
        "id": "why-distributed-sql",
        "title": {
          "en": "Why NewSQL — what it solves",
          "uk": "Навіщо NewSQL — яку проблему вирішує"
        }
      },
      {
        "id": "cockroachdb-yugabyte",
        "title": {
          "en": "CockroachDB & YugabyteDB",
          "uk": "CockroachDB та YugabyteDB"
        }
      },
      {
        "id": "tidb-htap",
        "title": {
          "en": "TiDB — HTAP with TiKV and TiFlash",
          "uk": "TiDB — HTAP з TiKV та TiFlash"
        }
      },
      {
        "id": "spanner-aurora-dsql",
        "title": {
          "en": "Google Spanner & Aurora DSQL",
          "uk": "Google Spanner та Aurora DSQL"
        }
      },
      {
        "id": "choosing-distributed-sql",
        "title": {
          "en": "Choosing a distributed SQL system",
          "uk": "Вибір distributed SQL системи"
        }
      }
    ]
  },
  {
    "id": "m31-analytics",
    "num": 31,
    "section": "s7-modern",
    "order": 3,
    "level": "senior",
    "signature": false,
    "title": {
      "en": "Analytics, columnar & time-series",
      "uk": "Аналітика, columnar і time-series"
    },
    "tagline": {
      "en": "Columnar + vectorized execution, ClickHouse & DuckDB, TimescaleDB/InfluxDB, the lakehouse.",
      "uk": "Columnar + vectorized execution, ClickHouse і DuckDB, TimescaleDB/InfluxDB, lakehouse."
    },
    "mentalModel": {
      "en": "Scan columns, not rows — OLAP is a different machine from OLTP.",
      "uk": "Скануйте колонки, а не рядки — OLAP — це інша машина, ніж OLTP."
    },
    "readMins": 12,
    "topics": [
      {
        "id": "columnar-execution",
        "title": {
          "en": "Columnar storage & vectorized execution",
          "uk": "Columnar storage та vectorized execution"
        }
      },
      {
        "id": "clickhouse-duckdb",
        "title": {
          "en": "ClickHouse & DuckDB — two ends of OLAP",
          "uk": "ClickHouse та DuckDB — два кінці OLAP"
        }
      },
      {
        "id": "time-series",
        "title": {
          "en": "Time-series: TimescaleDB & InfluxDB 3",
          "uk": "Time-series: TimescaleDB та InfluxDB 3"
        }
      },
      {
        "id": "lakehouse",
        "title": {
          "en": "The lakehouse: separating storage & compute",
          "uk": "Lakehouse: розділення storage та compute"
        }
      }
    ]
  },
  {
    "id": "m32-cloud-native",
    "num": 32,
    "section": "s7-modern",
    "order": 4,
    "level": "senior",
    "signature": false,
    "title": {
      "en": "Cloud-native & the modern DBA",
      "uk": "Cloud-native і сучасний DBA"
    },
    "tagline": {
      "en": "Managed DBs, Docker/K8s operators, IaC, observability, autoscaling.",
      "uk": "Керовані БД, Docker/K8s operators, IaC, observability, autoscaling."
    },
    "mentalModel": {
      "en": "The DBA moved up the stack — from tuning disks to wiring platforms.",
      "uk": "DBA піднявся стеком — від тюнінгу дисків до звʼязування платформ."
    },
    "readMins": 11,
    "topics": [
      {
        "id": "managed-databases",
        "title": {
          "en": "Managed databases: what you give up & gain",
          "uk": "Керовані бази даних: що віддаєте і що отримуєте"
        }
      },
      {
        "id": "containers-operators",
        "title": {
          "en": "Containers & Kubernetes operators",
          "uk": "Контейнери та Kubernetes operators"
        }
      },
      {
        "id": "iac",
        "title": {
          "en": "Infrastructure as code",
          "uk": "Infrastructure as code"
        }
      },
      {
        "id": "observability",
        "title": {
          "en": "Observability & the modern DBA dashboard",
          "uk": "Observability та дашборд сучасного DBA"
        }
      }
    ]
  },
  {
    "id": "m33-security",
    "num": 33,
    "section": "s8-mastery",
    "order": 1,
    "level": "senior",
    "signature": true,
    "title": {
      "en": "Security & data protection",
      "uk": "Безпека та захист даних"
    },
    "tagline": {
      "en": "AuthN/Z, RBAC/RLS, encryption at rest/in transit, hashing, SQL injection, least privilege.",
      "uk": "AuthN/Z, RBAC/RLS, шифрування at rest/in transit, hashing, SQL injection, least privilege."
    },
    "mentalModel": {
      "en": "Treat every input as hostile and grant the least privilege that works.",
      "uk": "Вважайте кожен вхід ворожим і давайте найменші привілеї, що працюють."
    },
    "readMins": 14,
    "topics": [
      {
        "id": "authn-authz",
        "title": {
          "en": "Authentication, authorization & least privilege",
          "uk": "Автентифікація, авторизація та least privilege"
        }
      },
      {
        "id": "rls",
        "title": {
          "en": "Row-level security (RLS)",
          "uk": "Row-level security (RLS)"
        }
      },
      {
        "id": "encryption",
        "title": {
          "en": "Encryption at rest & in transit",
          "uk": "Шифрування at rest та in transit"
        }
      },
      {
        "id": "passwords-secrets",
        "title": {
          "en": "Password hashing & secrets",
          "uk": "Hashing паролів та secrets"
        }
      },
      {
        "id": "sql-injection",
        "title": {
          "en": "SQL injection & a hardening checklist",
          "uk": "SQL injection та чек-лист hardening"
        }
      }
    ]
  },
  {
    "id": "m34-performance",
    "num": 34,
    "section": "s8-mastery",
    "order": 2,
    "level": "senior",
    "signature": true,
    "title": {
      "en": "Performance engineering",
      "uk": "Інженерія продуктивності"
    },
    "tagline": {
      "en": "Measure→bottleneck→fix→verify, slow queries, pooling, N+1, caching, capacity.",
      "uk": "Measure→bottleneck→fix→verify, повільні запити, pooling, N+1, кешування, capacity."
    },
    "mentalModel": {
      "en": "Measure first — the database is usually I/O-bound, and the bottleneck is rarely where you guessed.",
      "uk": "Спершу вимірюйте — база зазвичай I/O-bound, і вузьке місце рідко там, де ви думали."
    },
    "readMins": 14,
    "topics": [
      {
        "id": "method",
        "title": {
          "en": "A method: measure → bottleneck → fix → verify",
          "uk": "Метод: measure → bottleneck → fix → verify"
        }
      },
      {
        "id": "slow-queries",
        "title": {
          "en": "Slow queries, EXPLAIN & the N+1 problem",
          "uk": "Повільні запити, EXPLAIN та проблема N+1"
        }
      },
      {
        "id": "pooling",
        "title": {
          "en": "Connection pooling",
          "uk": "Connection pooling"
        }
      },
      {
        "id": "caching-replicas",
        "title": {
          "en": "Caching layers & read replicas",
          "uk": "Шари кешування та read replicas"
        }
      },
      {
        "id": "capacity",
        "title": {
          "en": "Capacity: scale up, out, or change the model",
          "uk": "Capacity: scale up, out чи зміна моделі"
        }
      }
    ]
  },
  {
    "id": "m35-choosing",
    "num": 35,
    "section": "s8-mastery",
    "order": 3,
    "level": "senior",
    "signature": true,
    "title": {
      "en": "Choosing the right database",
      "uk": "Вибір правильної бази даних"
    },
    "tagline": {
      "en": "The decision framework, the questions that matter, workload walkthroughs, polyglot persistence, anti-patterns.",
      "uk": "Фреймворк рішення, питання, що мають значення, розбори workload, polyglot persistence, анти-патерни."
    },
    "mentalModel": {
      "en": "Requirements first, engine second — never résumé-driven.",
      "uk": "Спершу вимоги, потім движок — ніколи не résumé-driven."
    },
    "readMins": 14,
    "topics": [
      {
        "id": "framework",
        "title": {
          "en": "The framework: requirements first, engine second",
          "uk": "Фреймворк: спершу вимоги, потім движок"
        }
      },
      {
        "id": "questions",
        "title": {
          "en": "The questions that matter",
          "uk": "Питання, що мають значення"
        }
      },
      {
        "id": "walkthroughs",
        "title": {
          "en": "Workload walkthroughs",
          "uk": "Розбори workload"
        }
      },
      {
        "id": "polyglot",
        "title": {
          "en": "Polyglot persistence — and its cost",
          "uk": "Polyglot persistence — і її ціна"
        }
      },
      {
        "id": "anti-patterns",
        "title": {
          "en": "Anti-patterns: how database choices go wrong",
          "uk": "Анти-патерни: як вибір бази йде не так"
        }
      }
    ]
  },
  {
    "id": "m36-mental-models",
    "num": 36,
    "section": "s8-mastery",
    "order": 4,
    "level": "middle",
    "signature": false,
    "title": {
      "en": "Mental models gallery + glossary",
      "uk": "Галерея ментальних моделей + глосарій"
    },
    "tagline": {
      "en": "Every mental model to recall from memory, a bilingual glossary, and a one-page cheat-sheet.",
      "uk": "Кожна ментальна модель для пригадування з памʼяті, двомовний глосарій і шпаргалка на одну сторінку."
    },
    "mentalModel": {
      "en": "If you can redraw the picture from memory, you understand it.",
      "uk": "Якщо можете перемалювати картину з памʼяті — ви це розумієте."
    },
    "readMins": 10,
    "topics": [
      {
        "id": "how-to-use",
        "title": {
          "en": "How to use the mental models",
          "uk": "Як користуватися ментальними моделями"
        }
      },
      {
        "id": "cheatsheet-storage",
        "title": {
          "en": "Cheat-sheet — data, storage & indexing",
          "uk": "Шпаргалка — дані, зберігання та індекси"
        }
      },
      {
        "id": "cheatsheet-transactions",
        "title": {
          "en": "Cheat-sheet — transactions & concurrency",
          "uk": "Шпаргалка — транзакції та конкурентність"
        }
      },
      {
        "id": "cheatsheet-distribution",
        "title": {
          "en": "Cheat-sheet — distribution & choosing",
          "uk": "Шпаргалка — розподіл і вибір"
        }
      }
    ]
  }
];
